### ISSUE TITLE
Remove Env and Data

### ISSUE THREAD

**Issue by PoignardAzur** [linebender/masonry#8]
The Env class and the Data trait are vestigial by this point in the Masonry codebase.

There is currently no support for updating widgets when the Env is changed, and I have no intention of adding that support (Xilem [seems to be moving in the same direction](https://github.com/linebender/xilem/issues/7)). This means Env is basically just a way to pass a singleton around in Widget code.

We should remove Env and data, and just hardcode the values that we currently get from Env, with future plans to pass them as arguments or something. Frontend frameworks might still use something Env-like to get style data, but that'll be their responsibility.

**Comment by herkhinah** [comment]
I've refactored both of them out in #53

**Comment by DasLixou** [comment]
@PoignardAzur i think this can be closed because of #54 ?

**Comment by PoignardAzur** [comment]
Yup. I should probably do a cleanup run over issues before we migrate them to Xilem.
